# Generated by Django 3.1.6 on 2021-02-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipe',
            new_name='Funcionario',
        ),
    ]
