# Generated by Django 3.1.5 on 2021-02-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210222_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='posicao',
            field=models.CharField(choices=[('E', 'a esquerda'), ('D', 'a dieita')], default='E', max_length=1, verbose_name='Posição do Chart:'),
        ),
    ]
