# Generated by Django 3.1.5 on 2021-02-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='icone',
            field=models.CharField(choices=[('lni-star-filled', 'Estrela completa'), ('lni-star-filled', 'Meia estrela')], default='Estrela completa', max_length=16, verbose_name='Estrelas'),
        ),
    ]
